[2024-06-17T11:47:29.465+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T11:47:29.481+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_data_etl_v10.get_dataset_with_tags scheduled__2024-06-16T12:00:00+00:00 [queued]>
[2024-06-17T11:47:29.485+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_data_etl_v10.get_dataset_with_tags scheduled__2024-06-16T12:00:00+00:00 [queued]>
[2024-06-17T11:47:29.486+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-17T11:47:29.495+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): get_dataset_with_tags> on 2024-06-16 12:00:00+00:00
[2024-06-17T11:47:29.499+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_data_etl_v10', 'get_dataset_with_tags', 'scheduled__2024-06-16T12:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/data_etl_dag.py', '--cfg-path', '/tmp/tmpx6ikxd03']
[2024-06-17T11:47:29.500+0000] {standard_task_runner.py:91} INFO - Job 33: Subtask get_dataset_with_tags
[2024-06-17T11:47:29.501+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=562) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-17T11:47:29.502+0000] {standard_task_runner.py:63} INFO - Started process 564 to run task
[2024-06-17T11:47:29.526+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_data_etl_v10.get_dataset_with_tags scheduled__2024-06-16T12:00:00+00:00 [running]> on host 10482076056f
[2024-06-17T11:47:29.577+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Solarev Ruslan' AIRFLOW_CTX_DAG_ID='dag_data_etl_v10' AIRFLOW_CTX_TASK_ID='get_dataset_with_tags' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-16T12:00:00+00:00'
[2024-06-17T11:47:29.578+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T11:47:29.585+0000] {logging_mixin.py:188} INFO - Добавлена новая профессия: Администратор базы данных
[2024-06-17T11:47:42.623+0000] {logging_mixin.py:188} INFO - Добавлена новая профессия: ERP-программист
[2024-06-17T11:48:01.157+0000] {logging_mixin.py:188} INFO - Добавлена новая профессия: Тестировщик программного обеспечения (ПО)
[2024-06-17T11:48:16.483+0000] {logging_mixin.py:188} INFO - Добавлена новая профессия: Модератор форума
[2024-06-17T11:48:18.144+0000] {logging_mixin.py:188} INFO - Добавлена новая профессия: HTML-верстальщик
[2024-06-17T11:48:19.834+0000] {logging_mixin.py:188} INFO - Добавлена новая профессия: Системный администратор
[2024-06-17T11:48:34.139+0000] {logging_mixin.py:188} INFO - Добавлена новая профессия: IT-евангелист
[2024-06-17T11:48:35.553+0000] {logging_mixin.py:188} INFO - Добавлена новая профессия: Технический писатель
[2024-06-17T11:48:48.004+0000] {logging_mixin.py:188} INFO - Добавлена новая профессия: Администратор сайта
[2024-06-17T11:49:02.693+0000] {logging_mixin.py:188} INFO - Добавлена новая профессия: Бизнес-аналитик 
[2024-06-17T11:49:22.268+0000] {python.py:237} INFO - Done. Returned value was:                    Profession  ...                                               Tags
0   Администратор базы данных  ...  ['Работа с базами данных' '1C: Предприятие' 'В...
1   Администратор базы данных  ...  ['Деловая переписка' 'Обеспечение жизнедеятель...
2   Администратор базы данных  ...  ['Телефонные переговоры' 'Кассовые операции' '...
3   Администратор базы данных  ...  ['Деловая переписка' 'Делопроизводство' 'Орган...
4   Администратор базы данных  ...  ['1С' '1С программирование' 'Cистемы управлени...
..                        ...  ...                                                ...
0            Бизнес-аналитик   ...                                               None
1            Бизнес-аналитик   ...                                               None
2            Бизнес-аналитик   ...                                               None
3            Бизнес-аналитик   ...                                               None
4            Бизнес-аналитик   ...                                               None

[395 rows x 3 columns]
[2024-06-17T11:49:22.274+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-17T11:49:22.370+0000] {xcom.py:675} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-06-17T11:49:22.371+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 148, in serialize
    data, serialized_classname, version, is_serialized = _serializers[qn].serialize(o)
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serializers/pandas.py", line 49, in serialize
    table = pa.Table.from_pandas(o)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 4525, in pyarrow.lib.Table.from_pandas
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/pandas_compat.py", line 624, in dataframe_to_arrays
    arrays[i] = maybe_fut.result()
                ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/pandas_compat.py", line 598, in convert_column
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/pandas_compat.py", line 592, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/array.pxi", line 345, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 85, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'list' object", 'Conversion failed for column Tags with type object')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 486, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3197, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 246, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 673, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2024-06-17T11:49:22.376+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_data_etl_v10, task_id=get_dataset_with_tags, run_id=scheduled__2024-06-16T12:00:00+00:00, execution_date=20240616T120000, start_date=20240617T114729, end_date=20240617T114922
[2024-06-17T11:49:22.385+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 33 for task get_dataset_with_tags (Object of type DataFrame is not JSON serializable; 564)
[2024-06-17T11:49:22.402+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-17T11:49:22.414+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-17T11:49:22.416+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
