[2024-06-17T12:15:58.243+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T12:15:58.260+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_data_etl_v12.preprocess_data.filter_tags scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-17T12:15:58.264+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_data_etl_v12.preprocess_data.filter_tags scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-17T12:15:58.264+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-06-17T12:15:58.272+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): preprocess_data.filter_tags> on 2024-06-17 00:00:00+00:00
[2024-06-17T12:15:58.278+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_data_etl_v12', 'preprocess_data.filter_tags', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/data_etl_dag.py', '--cfg-path', '/tmp/tmpe1wi_weh']
[2024-06-17T12:15:58.279+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask preprocess_data.filter_tags
[2024-06-17T12:15:58.280+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2136) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-17T12:15:58.281+0000] {standard_task_runner.py:63} INFO - Started process 2141 to run task
[2024-06-17T12:15:58.308+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_data_etl_v12.preprocess_data.filter_tags scheduled__2024-06-17T00:00:00+00:00 [running]> on host 10482076056f
[2024-06-17T12:15:58.357+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Solarev Ruslan' AIRFLOW_CTX_DAG_ID='dag_data_etl_v12' AIRFLOW_CTX_TASK_ID='preprocess_data.filter_tags' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-17T12:15:58.357+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T12:15:58.363+0000] {logging_mixin.py:188} INFO - Index(['Profession', 'Link', 'Tags'], dtype='object')
[2024-06-17T12:15:58.363+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-17T12:15:58.370+0000] {logging_mixin.py:188} WARNING - <unknown>:1 SyntaxWarning: invalid escape sequence '\d'
[2024-06-17T12:15:58.364+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/data_preprocessing/filter_tags.py", line 19, in filter_tags
    top_tags = pd.read_csv("dags\data\Top_tags.csv")["Skill"].to_list()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dags\\data\\Top_tags.csv'
[2024-06-17T12:15:58.374+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_data_etl_v12, task_id=preprocess_data.filter_tags, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240617T121558, end_date=20240617T121558
[2024-06-17T12:15:58.381+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 45 for task preprocess_data.filter_tags ([Errno 2] No such file or directory: 'dags\\data\\Top_tags.csv'; 2141)
[2024-06-17T12:15:58.414+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-17T12:15:58.420+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
